version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - DATABASE_URL=postgres://postgres:postgres@localhost:5432/valex
    depends_on:
      - database
    networks:
      - valex-net

  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./database/scripts/001-cria-banco.sql:/docker-entrypoint-initdb.d/create_tables.sql
      - ./database/scripts/002-popula-dados.sql:/docker-entrypoint-initdb.d/fill_tables.sql
    networks:
      - valex-net

networks:
  valex-net:
    driver: bridge